# Generated by Django 6.0.2 on 2026-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_en_event_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='1f7f966b1c224cee9bded146d6be1542', max_length=64, unique=True),
        ),
    ]
