# Generated by Django 6.0.2 on 2026-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventcategory_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='29cad9403cec413c8f5d959c37b8579a', max_length=64, unique=True),
        ),
    ]
