# Generated by Django 6.0.2 on 2026-04-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='ceedac9cb8234044b5d8a7a470425e2e', max_length=64, unique=True),
        ),
    ]
