# Generated by Django 6.0.2 on 2026-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='5ee54333e1384c5b969037dfae21b3ea', max_length=64, unique=True),
        ),
    ]
