# Generated by Django 6.0.2 on 2026-04-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='764305bf3ca945c2a6fa7e01bb5aeb1b', max_length=64, unique=True),
        ),
    ]
