# Generated by Django 6.0.2 on 2026-04-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='dede30fa9f3d4f459ef6b293b869c7cb', max_length=64, unique=True),
        ),
    ]
