# Generated by Django 6.0.2 on 2026-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='3712209010e448df8dfabdfd4b5c0ee7', max_length=64, unique=True),
        ),
    ]
