# Generated by Django 6.0.2 on 2026-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='4c9c7ef91d8f4f40ad0a008691669d72', max_length=64, unique=True),
        ),
    ]
