# Generated by Django 6.0.2 on 2026-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='43e409a4f10e4e148e48510185ec8611', max_length=64, unique=True),
        ),
    ]
