# Generated by Django 6.0.2 on 2026-04-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='be1b5c1320dd4b54add8a2e2a6350aa9', max_length=64, unique=True),
        ),
    ]
