# Generated by Django 6.0.2 on 2026-04-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventslotinvite_token'),
        ('jobs', '0003_roletrainingrequirement_role_training_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventroleslot',
            name='role',
        ),
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='5fe28fc4cde249608c4e7fab833930a8', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='eventroleslot',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='jobs.role'),
            preserve_default=False,
        ),
    ]
