# Generated by Django 6.0.2 on 2026-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_eventroleslot_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='a2a263f40fd94ac28c8b29c3e1ffd41f', max_length=64, unique=True),
        ),
    ]
