# Generated by Django 6.0.2 on 2026-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='e995bb0d091f4b5ba85612793a5b1f29', max_length=64, unique=True),
        ),
    ]
