# Generated by Django 6.0.2 on 2026-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='c158fae3daf2474e8463574f881a1334', max_length=64, unique=True),
        ),
    ]
