# Generated by Django 6.0.2 on 2026-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='05d7c3edb4ff4e2491dc16acc29423cb', max_length=64, unique=True),
        ),
    ]
