# Generated by Django 6.0.2 on 2026-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='5bd7c6c0fd4442ee86398cfd92337fd2', max_length=64, unique=True),
        ),
    ]
