# Generated by Django 6.0.2 on 2026-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='f4594dfd74bc44699b59368b8ccea68a', max_length=64, unique=True),
        ),
    ]
