# Generated by Django 6.0.2 on 2026-04-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='0e13ab0cb57343a6bfb6074584c69550', max_length=64, unique=True),
        ),
    ]
