# Generated by Django 6.0.2 on 2026-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='68ea95d7c2284191b053965d94828521', max_length=64, unique=True),
        ),
    ]
