# Generated by Django 6.0.2 on 2026-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='f2a4b90cdd284468a7da87d68eee2b43', max_length=64, unique=True),
        ),
    ]
