# Generated by Django 6.0.2 on 2026-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='22895711144848e193d8523116a8342a', max_length=64, unique=True),
        ),
    ]
