# Generated by Django 6.0.2 on 2026-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='c774594075334ccf8fb0fe71fa4037ca', max_length=64, unique=True),
        ),
    ]
