# Generated by Django 6.0.2 on 2026-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='bbb1481d3f4649dd99a7f9e094bcd6f7', max_length=64, unique=True),
        ),
    ]
