# Generated by Django 6.0.2 on 2026-04-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report_to_location',
            field=models.CharField(blank=True, help_text='Where volunteers should report to inside the location venue', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='856132f826994391840ec08159d97909', max_length=64, unique=True),
        ),
    ]
