# Generated by Django 6.0.2 on 2026-04-30 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_report_to_location_alter_eventslotinvite_token'),
        ('jobs', '0004_alter_role_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Optional role reference for shifts that are not tied to a specific event role slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='jobs.role'),
        ),
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='8d4fef51cae54872bfeeadb4d6003389', max_length=64, unique=True),
        ),
    ]
