# Generated by Django 6.0.2 on 2026-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_shift_role_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='d8b6bc86569449599aa4cf46a6026505', max_length=64, unique=True),
        ),
    ]
