# Generated by Django 6.0.2 on 2026-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='a2a7da32bf1f44118ac1f0d94560ea82', max_length=64, unique=True),
        ),
    ]
