# Generated by Django 6.0.2 on 2026-06-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_remove_shift_from_events_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='1b786b992f2a4d229dbc7ca69e5278ac', max_length=64, unique=True),
        ),
    ]
