# Generated by Django 6.0.2 on 2026-07-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='211dc239d9764953af1e4c71797fd518', max_length=64, unique=True),
        ),
    ]
