# Generated by Django 6.0.2 on 2026-07-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0, help_text='Number of attendees (for calculating impact points)'),
        ),
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='e99a54f736ad47fba94295cd5874d719', max_length=64, unique=True),
        ),
    ]
