# Generated by Django 6.0.2 on 2026-07-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_event_attendees_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='e15e17a495db4495bf91d4ee47799b5b', max_length=64, unique=True),
        ),
    ]
