# Generated by Django 6.0.2 on 2026-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_eventslotinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslotinvite',
            name='token',
            field=models.CharField(default='817ca0d0f0e948aab733bbc5dc33e10d', max_length=64, unique=True),
        ),
    ]
