# Generated by Django 6.0.2 on 2026-10-06 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_venues'),
        ('events', '0037_event_published_alter_eventslotinvite_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Where the event takes place. Leave blank and fill in location for a one-off address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='base.venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_es',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_fr',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_uk',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200, null=True),
        ),
    ]
