# Generated by Django 6.0.2 on 2026-10-06 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_link_events_to_venues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_minute', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_log', to='events.eventroleslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('slot', 'user')},
            },
        ),
    ]
