# Generated by Django 6.0.2 on 2026-10-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_slotsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('planning', 'Planning'), ('event', 'During the event')], default='event', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('belltower_url', models.URLField()),
                ('belltower_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='events.event')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('belltower_url', 'belltower_id'), name='unique_belltower_list')],
            },
        ),
    ]
