# Generated by Django 6.0.2 on 2026-10-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_eventtasklist'),
        ('jobs', '0013_role_points_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtasklist',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_task_lists', to='jobs.role'),
        ),
        migrations.AddConstraint(
            model_name='eventtasklist',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('event', 'role', 'belltower_url'), name='one_list_per_event_role'),
        ),
    ]
