# Generated by Django 6.0.2 on 2026-10-08 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_eventtasklist_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chain_of_command',
            field=models.BooleanField(default=False, help_text='Group roles into areas with area and shift leads'),
        ),
        migrations.AddField(
            model_name='event',
            name='leads_auto_assigned_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When open shift lead positions were filled automatically', null=True),
        ),
        migrations.AddField(
            model_name='eventroleslot',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventroleslot',
            name='lead_auto_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_es', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_uk', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Icon name from Google Material Symbols', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='events.event')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AreaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_leads', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='events.eventarea')),
            ],
            options={
                'ordering': ['start_time', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='eventroleslot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='events.eventarea'),
        ),
        migrations.AddField(
            model_name='eventtasklist',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_lists', to='events.eventarea'),
        ),
    ]
