# Generated by Django 6.0.2 on 2026-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_area_leads_as_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_tl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_tl',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_zh_hant',
            field=models.CharField(blank=True, default='', help_text='One-off address, used when no venue is chosen', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='post_event_statement_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='post_event_statement_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='name_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
