# Generated by Django 6.0.2 on 2026-03-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Icon name from Google Material Icons', max_length=50)),
                ('permanent', models.BooleanField(default=False)),
            ],
        ),
    ]
