# Generated by Django 6.0.2 on 2026-04-02 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_trainingmodule_required'),
        ('jobs', '0002_role_description_en_role_description_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.role')),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.trainingmodule')),
            ],
            options={
                'unique_together': {('role', 'training_module')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='training_modules',
            field=models.ManyToManyField(blank=True, related_name='roles', through='jobs.RoleTrainingRequirement', to='education.trainingmodule'),
        ),
    ]
