# Generated by Django 6.0.2 on 2026-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_roletrainingrequirement_role_training_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permanent',
            field=models.BooleanField(default=False, help_text='Whether this role is a permanent position (not tied to specific events)'),
        ),
    ]
