# Generated by Django 6.0.2 on 2026-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_role_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='regular_number_of_beneficiaries',
            field=models.PositiveIntegerField(blank=True, help_text='Typical number of beneficiaries served by this role per shift (used for impact points calculation for permanent roles)', null=True),
        ),
    ]
