# Generated by Django 6.0.2 on 2026-07-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_shift_table_to_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='clutched',
            field=models.BooleanField(default=False, help_text='Whether this shift was clutched (i.e., the user stepped in to cover a shift at the last minute)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='regular_number_of_beneficiaries',
            field=models.PositiveIntegerField(blank=True, help_text='Typical number of beneficiaries served by this role per hour (used for impact points calculation for permanent roles)', null=True),
        ),
    ]
