# Generated by Django 6.0.2 on 2026-07-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_shift_clutched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_impact_points',
            field=models.IntegerField(blank=True, help_text='Impact points calculated at the end of the shift', null=True),
        ),
    ]
