# Generated by Django 6.0.2 on 2026-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_operatinghour'),
        ('jobs', '0009_shift_end_impact_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='venue',
            field=models.ManyToManyField(blank=True, help_text='Venues where this role is applicable. Leave blank if the role is not venue-specific.', related_name='roles', to='base.venue'),
        ),
    ]
