# Generated by Django 6.0.2 on 2026-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_externalcertificate_issuer_and_more'),
        ('jobs', '0010_role_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, help_text='Non-mandatory skills that improve volunteer matching', related_name='preferred_for_roles', to='education.skill'),
        ),
    ]
