# Generated by Django 6.0.2 on 2026-10-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_operatinghour_open_to_staff_outside_hours_and_more'),
        ('jobs', '0011_role_preferred_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='venue',
            field=models.ManyToManyField(blank=True, help_text='Venues where this role is applicable. Leave blank if the role is not venue-specific. Used mainly for permanent roles.', related_name='roles', to='base.venue'),
        ),
    ]
