# Generated by Django 6.0.2 on 2026-10-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_role_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='points_weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Impact points multiplier. Leave empty to set it from training length.', max_digits=3, null=True),
        ),
    ]
