# Generated by Django 6.0.2 on 2026-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_role_points_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='system_key',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
