# Generated by Django 6.0.2 on 2026-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_area_lead_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_tl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
