# Generated by Django 6.0.2 on 2026-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='06b5bb017bd54ed883247902536e34be', max_length=40, unique=True),
        ),
    ]
