# Generated by Django 6.0.2 on 2026-10-05 08:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=api.models.generate_key, max_length=40, unique=True),
        ),
    ]
