# Generated by Django 6.0.2 on 2026-03-23 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(blank=True, max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_true_false', models.BooleanField(default=False)),
                ('length_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('icon', models.CharField(help_text='Icon name from Google Material Icons', max_length=50)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_training_modules', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='training_modules', to='education.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_length_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_lessons', to=settings.AUTH_USER_MODEL)),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.trainingmodule')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_quizzes', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='quizzes', to='education.quizquestion')),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='education.trainingmodule')),
            ],
        ),
    ]
