# Generated by Django 6.0.2 on 2026-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
