# Generated by Django 6.0.2 on 2026-04-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_quiz_title_en_quiz_title_es_quiz_title_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
