# Generated by Django 6.0.2 on 2026-04-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_trainingmodule_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='required',
        ),
    ]
