# Generated by Django 6.0.2 on 2026-04-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_trainingmodule_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='quiz',
            name='percentage_to_pass',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='expires_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days after which the training module expires for a user', null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='training_module_photos/'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='started_by',
            field=models.ManyToManyField(blank=True, related_name='started_training_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='skills',
            field=models.ManyToManyField(related_name='courses', to='education.skill'),
        ),
        migrations.CreateModel(
            name='TrainingModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='education.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_module_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('training_module', 'user')},
            },
        ),
    ]
