# Generated by Django 6.0.2 on 2026-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_trainingtopic_trainingmodule_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtopic',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
