# Generated by Django 6.0.2 on 2026-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_trainingtopic_name_en_trainingtopic_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
