# Generated by Django 6.0.2 on 2026-04-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_externalcertificate_usercertification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertification',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.externalcertificate'),
        ),
    ]
