# Generated by Django 6.0.2 on 2026-04-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_usercertification_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertification',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
