# Generated by Django 6.0.2 on 2026-04-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_usercertification_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercertification',
            old_name='confirmed',
            new_name='verified',
        ),
    ]
