# Generated by Django 6.0.2 on 2026-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_rename_confirmed_usercertification_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcertificate',
            name='docs_list',
            field=models.TextField(blank=True, help_text='List of required documents for this certificate, separated by commas', null=True),
        ),
    ]
