# Generated by Django 6.0.2 on 2026-04-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_externalcertificate_docs_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcertificate',
            name='icon',
            field=models.CharField(blank=True, help_text='Material Symbols icon name for this certificate', max_length=50, null=True),
        ),
    ]
