# Generated by Django 6.0.2 on 2026-07-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_externalcertificate_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='complexity_level',
            field=models.PositiveIntegerField(default=0, help_text='Complexity level of the training module (0-4)'),
        ),
    ]
