# Generated by Django 6.0.2 on 2026-10-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_trainingmodule_complexity_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcertificate',
            name='issuer',
            field=models.CharField(blank=True, default='', help_text='Issuing authority, e.g. "American Red Cross"', max_length=100),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Private reviewer notes'),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date printed on the external certificate', null=True),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='rejected',
            field=models.BooleanField(default=False, help_text='Set when staff rejected the submitted documents'),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercertification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
