# Generated by Django 6.0.2 on 2026-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_externalcertificate_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_tl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_tl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_tl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_tl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_tl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_text_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_tl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='content_tl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='content_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='title_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description_tl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='title_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='name_tl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
