# Generated by Django 5.0.7 on 2026-02-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primary', models.CharField(default='#0D7377', help_text='Teal - main brand color', max_length=7)),
                ('color_primary_dark', models.CharField(default='#065A5C', help_text='Darker teal for hover states', max_length=7)),
                ('color_primary_light', models.CharField(default='#14919B', help_text='Lighter teal for accents', max_length=7)),
                ('color_accent', models.CharField(default='#F26B5B', help_text='Coral/Orange - CTAs and highlights', max_length=7)),
                ('color_accent_dark', models.CharField(default='#E05545', help_text='Darker coral for hover states', max_length=7)),
                ('color_accent_light', models.CharField(default='#FF8575', help_text='Lighter coral', max_length=7)),
                ('color_bg_primary', models.CharField(default='#E8F6F3', help_text='Light mint/seafoam background', max_length=7)),
                ('color_bg_secondary', models.CharField(default='#F5FAFA', help_text='Very light teal tint', max_length=7)),
                ('color_bg_white', models.CharField(default='#FFFFFF', help_text='White for cards', max_length=7)),
                ('color_bg_dark', models.CharField(default='#0D7377', help_text='Dark teal for dark sections', max_length=7)),
                ('color_text_primary', models.CharField(default='#1A2E35', help_text='Dark navy - main text', max_length=7)),
                ('color_text_secondary', models.CharField(default='#4A6670', help_text='Muted text', max_length=7)),
                ('color_text_light', models.CharField(default='#7A9BA5', help_text='Light text for captions', max_length=7)),
                ('color_text_white', models.CharField(default='#FFFFFF', help_text='White text on dark backgrounds', max_length=7)),
                ('color_border', models.CharField(default='#D1E3E0', help_text='Light teal border', max_length=7)),
                ('color_divider', models.CharField(default='#E0EEEC', help_text='Subtle divider', max_length=7)),
                ('color_success', models.CharField(default='#28A745', help_text='Green for success', max_length=7)),
                ('color_warning', models.CharField(default='#FFC107', help_text='Yellow for warnings', max_length=7)),
                ('color_error', models.CharField(default='#DC3545', help_text='Red for errors', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
