# Generated by Django 5.0.7 on 2026-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dark_bg_primary',
            field=models.CharField(default='#0F1419', help_text='Dark mode - primary background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_bg_secondary',
            field=models.CharField(default='#1A2632', help_text='Dark mode - secondary background (cards)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_bg_tertiary',
            field=models.CharField(default='#243447', help_text='Dark mode - tertiary background (elevated)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_border',
            field=models.CharField(default='#38444D', help_text='Dark mode - border color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_divider',
            field=models.CharField(default='#2F3B47', help_text='Dark mode - divider color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_text_primary',
            field=models.CharField(default='#F7F9F9', help_text='Dark mode - primary text', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_text_secondary',
            field=models.CharField(default='#8B98A5', help_text='Dark mode - secondary/muted text', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_text_tertiary',
            field=models.CharField(default='#6E7A85', help_text='Dark mode - tertiary/disabled text', max_length=7),
        ),
    ]
