# Generated by Django 6.0.2 on 2026-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitesettings_dark_bg_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Company Name', help_text='Name of the company or organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent',
            field=models.CharField(default='#F26B5B', help_text='Call-to-action buttons and highlights', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_dark',
            field=models.CharField(default='#E05545', help_text='Darker variant for hover states', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_light',
            field=models.CharField(default='#FF8575', help_text='Lighter variant for subtle accents', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_dark',
            field=models.CharField(default='#0D7377', help_text='Dark sections (footer, headers)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_primary',
            field=models.CharField(default='#E8F6F3', help_text='Main page background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_secondary',
            field=models.CharField(default='#F5FAFA', help_text='Secondary/alternate background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_white',
            field=models.CharField(default='#FFFFFF', help_text='Card and surface background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_border',
            field=models.CharField(default='#D1E3E0', help_text='Input and card borders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_divider',
            field=models.CharField(default='#E0EEEC', help_text='Subtle section dividers', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_error',
            field=models.CharField(default='#DC3545', help_text='Error messages and indicators', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary',
            field=models.CharField(default='#0D7377', help_text='Main brand color', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_dark',
            field=models.CharField(default='#065A5C', help_text='Darker variant for hover states', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_light',
            field=models.CharField(default='#14919B', help_text='Lighter variant for accents', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_success',
            field=models.CharField(default='#28A745', help_text='Success messages and indicators', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_light',
            field=models.CharField(default='#7A9BA5', help_text='Captions and placeholders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_primary',
            field=models.CharField(default='#1A2E35', help_text='Main body text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_secondary',
            field=models.CharField(default='#4A6670', help_text='Muted/secondary text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_white',
            field=models.CharField(default='#FFFFFF', help_text='Text on dark backgrounds', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_warning',
            field=models.CharField(default='#FFC107', help_text='Warning messages and indicators', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_bg_primary',
            field=models.CharField(default='#0F1419', help_text='Main page background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_bg_secondary',
            field=models.CharField(default='#1A2632', help_text='Card and surface background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_bg_tertiary',
            field=models.CharField(default='#243447', help_text='Elevated surfaces (modals, dropdowns)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_border',
            field=models.CharField(default='#38444D', help_text='Input and card borders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_divider',
            field=models.CharField(default='#2F3B47', help_text='Subtle section dividers', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_text_primary',
            field=models.CharField(default='#F7F9F9', help_text='Main body text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_text_secondary',
            field=models.CharField(default='#8B98A5', help_text='Muted/secondary text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_text_tertiary',
            field=models.CharField(default='#6E7A85', help_text='Disabled text and placeholders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
