# Generated by Django 6.0.2 on 2026-03-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_alter_sitesettings_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Town Hall', max_length=50)),
                ('title_en', models.CharField(default='Welcome to Our Town Hall', max_length=50, null=True)),
                ('title_es', models.CharField(default='Welcome to Our Town Hall', max_length=50, null=True)),
                ('title_fr', models.CharField(default='Welcome to Our Town Hall', max_length=50, null=True)),
                ('title_uk', models.CharField(default='Welcome to Our Town Hall', max_length=50, null=True)),
                ('subtitle', models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150)),
                ('subtitle_en', models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150, null=True)),
                ('subtitle_es', models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150, null=True)),
                ('subtitle_fr', models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150, null=True)),
                ('subtitle_uk', models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('button_1_text', models.CharField(default='Learn More', max_length=20)),
                ('button_1_text_en', models.CharField(default='Learn More', max_length=20, null=True)),
                ('button_1_text_es', models.CharField(default='Learn More', max_length=20, null=True)),
                ('button_1_text_fr', models.CharField(default='Learn More', max_length=20, null=True)),
                ('button_1_text_uk', models.CharField(default='Learn More', max_length=20, null=True)),
                ('button_1_url', models.URLField(default='#')),
                ('button_2_text', models.CharField(default='Get Involved', max_length=20)),
                ('button_2_text_en', models.CharField(default='Get Involved', max_length=20, null=True)),
                ('button_2_text_es', models.CharField(default='Get Involved', max_length=20, null=True)),
                ('button_2_text_fr', models.CharField(default='Get Involved', max_length=20, null=True)),
                ('button_2_text_uk', models.CharField(default='Get Involved', max_length=20, null=True)),
                ('button_2_url', models.URLField(default='#')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
