# Generated by Django 6.0.2 on 2026-03-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_herosection_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent',
            field=models.CharField(default='#ac3509', help_text='Call-to-action buttons and highlights', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_dark',
            field=models.CharField(default='#8a2b07', help_text='Darker variant for hover states', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_light',
            field=models.CharField(default='#c74a1e', help_text='Lighter variant for subtle accents', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_dark',
            field=models.CharField(default='#00434d', help_text='Dark sections (footer, headers)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_primary',
            field=models.CharField(default='#ebfdfc', help_text='Main page background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_secondary',
            field=models.CharField(default='#dff1f0', help_text='Secondary/alternate background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_white',
            field=models.CharField(default='#e5f5f4', help_text='Card and surface background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_border',
            field=models.CharField(default='#ccdedd', help_text='Input and card borders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_divider',
            field=models.CharField(default='#dff1f0', help_text='Subtle section dividers', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary',
            field=models.CharField(default='#00434d', help_text='Main brand color', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_dark',
            field=models.CharField(default='#005c69', help_text='Darker variant for hover states', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_light',
            field=models.CharField(default='#84f5e8', help_text='Lighter variant for accents', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_light',
            field=models.CharField(default='#6b8a8a', help_text='Captions and placeholders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_primary',
            field=models.CharField(default='#0e1e1e', help_text='Main body text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_secondary',
            field=models.CharField(default='#3a5454', help_text='Muted/secondary text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text_white',
            field=models.CharField(default='#ebfdfc', help_text='Text on dark backgrounds', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_bg_primary',
            field=models.CharField(default='#011a1d', help_text='Main page background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_bg_secondary',
            field=models.CharField(default='#022a2e', help_text='Card and surface background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_bg_tertiary',
            field=models.CharField(default='#033b40', help_text='Elevated surfaces (modals, dropdowns)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_border',
            field=models.CharField(default='#064e56', help_text='Input and card borders', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_divider',
            field=models.CharField(default='#043f47', help_text='Subtle section dividers', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_text_primary',
            field=models.CharField(default='#ebfdfc', help_text='Main body text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_text_secondary',
            field=models.CharField(default='#84f5e8', help_text='Muted/secondary text', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dark_text_tertiary',
            field=models.CharField(default='#5db8ad', help_text='Disabled text and placeholders', max_length=7),
        ),
    ]
