# Generated by Django 6.0.2 on 2026-04-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_accent_dark',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_accent_light',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_primary_dark',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_primary_light',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_dark_offset',
            field=models.PositiveSmallIntegerField(default=2, help_text='Darker variant offset for hover states'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_light_offset',
            field=models.PositiveSmallIntegerField(default=4, help_text='Lighter variant offset for hover states'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary_dark_offset',
            field=models.PositiveSmallIntegerField(default=2, help_text='Darker variant offset for hover states'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary_light_offset',
            field=models.PositiveSmallIntegerField(default=4, help_text='Lighter variant offset for hover states'),
        ),
    ]
