# Generated by Django 6.0.2 on 2026-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_sitesettings_color_accent_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_bg_dark',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_bg_white',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_text_light',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='color_text_white',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_bg_tertiary',
            field=models.CharField(default='#e5f5f4', help_text='Elevated surfaces (cards, modals)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_text_tertiary',
            field=models.CharField(default='#6b8a8a', help_text='Captions and disabled text', max_length=7),
        ),
    ]
