# Generated by Django 6.0.2 on 2026-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_sitesettings_color_bg_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_contrast',
            field=models.CharField(default='#ffffff', help_text='Text color on accent background', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary_contrast',
            field=models.CharField(default='#ffffff', help_text='Text color on primary background', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_bg_tertiary',
            field=models.CharField(default='#d7e7e6', help_text='Elevated surfaces (cards, modals)', max_length=7),
        ),
    ]
