# Generated by Django 6.0.2 on 2026-04-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_sitesettings_color_accent_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='careers_page_url',
            field=models.URLField(default='https://www.example.com/careers', help_text='URL for the careers page'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_contrast',
            field=models.CharField(default='#ffffff', help_text='Color that contrasts well with the primary accent color for text and icons', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_dark_offset',
            field=models.PositiveSmallIntegerField(default=20, help_text='Darker variant offset for hover states'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_accent_light_offset',
            field=models.PositiveSmallIntegerField(default=40, help_text='Lighter variant offset for hover states'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_contrast',
            field=models.CharField(default='#ffffff', help_text='Color that contrasts well with the primary color for text and icons', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_dark_offset',
            field=models.PositiveSmallIntegerField(default=20, help_text='Darker variant offset for hover states'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_primary_light_offset',
            field=models.PositiveSmallIntegerField(default=40, help_text='Lighter variant offset for hover states'),
        ),
    ]
