# Generated by Django 6.0.2 on 2026-04-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_sitesettings_careers_page_url_and_more'),
        ('education', '0005_remove_trainingmodule_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_viewed_training_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_by_profiles', to='education.trainingmodule'),
        ),
    ]
