# Generated by Django 6.0.2 on 2026-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_profile_last_viewed_training_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('numeric_name', models.PositiveIntegerField(help_text='Numeric representation of the level for ordering (e.g., Level 1, Level 2)', unique=True)),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('benefits', models.TextField(blank=True, help_text='Description of benefits for this level as a comma-separated list.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='impact_points',
            field=models.IntegerField(default=0),
        ),
    ]
