# Generated by Django 6.0.2 on 2026-04-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_level_profile_impact_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='max_points',
        ),
    ]
