# Generated by Django 6.0.2 on 2026-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_level_max_points'),
        ('jobs', '0004_alter_role_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permanent_roles',
            field=models.ManyToManyField(blank=True, related_name='staff', to='jobs.role'),
        ),
    ]
