# Generated by Django 6.0.2 on 2026-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_profile_permanent_roles'),
        ('education', '0014_externalcertificate_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='education.skill'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_skills_per_user',
            field=models.PositiveSmallIntegerField(default=10, help_text='Maximum number of skills a user can add to their profile'),
        ),
    ]
