# Generated by Django 6.0.2 on 2026-07-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_code',
            field=models.CharField(default='', editable=False, help_text='Unique identifier for the user (e.g., employee ID, volunteer ID)', max_length=6),
        ),
    ]
