# Generated by Django 6.0.2 on 2026-07-05 01:41

from django.db import migrations, models
import uuid


def populate_id_codes(apps, schema_editor):
    """Generate unique id_codes for existing profiles"""
    Profile = apps.get_model('base', 'Profile')
    for profile in Profile.objects.all():
        if not profile.id_code or profile.id_code == '':
            profile.id_code = str(uuid.uuid4())[:6].upper()
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_profile_id_code'),
    ]

    operations = [
        migrations.RunPython(populate_id_codes),
        migrations.AlterField(
            model_name='profile',
            name='id_code',
            field=models.CharField(editable=False, help_text='Unique identifier for the user (e.g., employee ID, volunteer ID)', max_length=6, unique=True),
        ),
    ]
