# Generated by Django 6.0.2 on 2026-07-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_profile_id_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kiosk_idle_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=30, help_text='Idle time in seconds before kiosk sessions are automatically logged out'),
        ),
    ]
