# Generated by Django 6.0.2 on 2026-10-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_operatinghour'),
        ('events', '0037_event_published_alter_eventslotinvite_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event the endorsement relates to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements', to='events.event'),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes visible to staff only'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo (PNG or SVG)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service',
            field=models.TextField(blank=True, default='', help_text='Terms of service shown to volunteers (Markdown)'),
        ),
        migrations.CreateModel(
            name='AdminFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_admin_feedback', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
