# Generated by Django 6.0.2 on 2026-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_backfill_missing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='deepl_api_key',
            field=models.CharField(blank=True, default='', help_text='DeepL API key (free-tier keys end in ":fx")', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', help_text='Sender address for invitations and password resets', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, default='', help_text='SMTP server. Leave blank to print emails to the server console.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_translate_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Cloud Translation API key', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='libretranslate_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='libretranslate_url',
            field=models.URLField(blank=True, default='', help_text='Your LibreTranslate server, e.g. http://translate.internal:5000'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mymemory_email',
            field=models.EmailField(blank=True, default='', help_text='Raises the free MyMemory limit to about 50,000 characters a day', max_length=254),
        ),
    ]
