# Generated by Django 6.0.2 on 2026-10-05 23:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_numeric_kiosk_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinghour',
            name='open_to_staff_outside_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_photos/'),
        ),
        migrations.CreateModel(
            name='VenueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_after', models.DurationField(default=datetime.timedelta(days=7))),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.venue')),
            ],
        ),
    ]
