# Generated by Django 6.0.2 on 2026-10-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_operatinghour_open_to_staff_outside_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_es', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_uk', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(default='check_circle', help_text='Google Material Symbols icon name', max_length=50)),
                ('category', models.CharField(choices=[('facilities', 'Facilities'), ('accessibility', 'Accessibility'), ('equipment', 'Equipment & tech'), ('getting_there', 'Getting there')], default='facilities', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='venues', to='base.venuefeature'),
        ),
    ]
