# Generated by Django 6.0.2 on 2026-10-06 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_endorsement_skills'),
        ('education', '0016_externalcertificate_issuer_and_more'),
        ('events', '0040_slotsignup'),
        ('jobs', '0013_role_points_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_hour', models.PositiveIntegerField(default=10, help_text='Base points for every hour worked')),
                ('max_role_weight', models.DecimalField(decimal_places=1, default=2.0, help_text='Multiplier for the most demanding roles (by training length); the easiest get 1.0', max_digits=3)),
                ('reach_cap_percent', models.PositiveIntegerField(default=50, help_text='Largest bonus for serving many people')),
                ('walk_in_bonus_percent', models.PositiveIntegerField(default=50, help_text='Covering an open slot at the kiosk without signing up')),
                ('last_minute_bonus_percent', models.PositiveIntegerField(default=25, help_text='Signing up for an understaffed slot shortly before it starts')),
                ('last_minute_window_hours', models.PositiveIntegerField(default=24)),
                ('off_hours_bonus_percent', models.PositiveIntegerField(default=25, help_text='Shifts that start early or end late')),
                ('early_start_hour', models.PositiveSmallIntegerField(default=7, help_text='Shifts starting before this hour get the off-hours bonus')),
                ('late_end_hour', models.PositiveSmallIntegerField(default=22, help_text='Shifts ending after this hour get the off-hours bonus')),
                ('training_points_per_minute', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('training_points_min', models.PositiveIntegerField(default=5, help_text='Smallest award for finishing a module')),
                ('training_points_cap', models.PositiveIntegerField(default=60, help_text='Largest award for finishing a module')),
                ('endorsement_points', models.PositiveIntegerField(default=5, help_text='Awarded to someone endorsed by a teammate from the same event')),
                ('endorsement_monthly_cap', models.PositiveIntegerField(default=5, help_text='Endorsement awards a person can earn in 30 days')),
            ],
            options={
                'verbose_name_plural': 'Points rules',
            },
        ),
        migrations.CreateModel(
            name='PointsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(choices=[('shift', 'Shift'), ('training', 'Training'), ('endorsement', 'Endorsement'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', help_text='Shown for manual adjustments', max_length=200)),
                ('details', models.JSONField(blank=True, default=dict, help_text='How the amount was worked out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('endorsement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.endorsement')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event')),
                ('shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_entry', to='jobs.shift')),
                ('training_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='education.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Points entries',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
