# Generated by Django 6.0.2 on 2026-10-06 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_pointsrules_pointsentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the points were earned'),
        ),
    ]
