# Generated by Django 6.0.2 on 2026-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_pointsentry_earned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_1_url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_2_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
