# Generated by Django 6.0.2 on 2026-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_hero_button_urls_as_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='belltower_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='belltower_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='belltower_endpoints',
            field=models.JSONField(blank=True, default=dict, help_text='From /.well-known/belltower'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='belltower_url',
            field=models.URLField(blank=True, default='', help_text='Bell Tower server, e.g. https://tasks.example.org'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='belltower_username',
            field=models.CharField(blank=True, default='', help_text='Bell Tower account Town Hall acts as', max_length=150),
        ),
    ]
