# Generated by Django 6.0.2 on 2026-10-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_belltowerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='Comma-separated language codes that are switched on', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='time_zone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
