# Generated by Django 6.0.2 on 2026-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_site_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='button_1_text_tl',
            field=models.CharField(default='Learn More', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_1_text_zh_hant',
            field=models.CharField(default='Learn More', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_2_text_tl',
            field=models.CharField(default='Get Involved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_2_text_zh_hant',
            field=models.CharField(default='Get Involved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_tl',
            field=models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_zh_hant',
            field=models.TextField(default='Engage with your community and stay informed about local news and events.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_tl',
            field=models.CharField(default='Welcome to Our Town Hall', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_zh_hant',
            field=models.CharField(default='Welcome to Our Town Hall', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venuefeature',
            name='name_tl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venuefeature',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
