# Generated by Django 6.0.2 on 2026-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_traditional_chinese_tagalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_planner_hidden',
            field=models.BooleanField(default=False, help_text='Dismissed the "Help me plan" button on event pages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_enabled',
            field=models.BooleanField(default=False, help_text='Turn on AI features such as the event planning assistant'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_model',
            field=models.CharField(blank=True, default='claude-opus-5-5', help_text='Claude model the assistant uses', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, default='', help_text='Anthropic API key', max_length=200),
        ),
    ]
